// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router'

// Import routes
import { Route as IndexRoute } from './routes/index'

// Create route tree
export const routeTree = IndexRoute.addChildren([])